name: "My Project"
description: "My project description"

# Supported

gradle:
  projects:
    - name: "architect-cli"

semantic-release:
  assets:
    - path: ./architect-cli/build/libs/architect-cli-0.1-all.jar
      name: architect-cli.jar

# A list of other configurations that one day will be supported

project:
  name: "architect"
  description: "A simple project generator"
  version: "0.1.0"
  license: "MIT"

plugins:
  - owner: "alemazzo"
    repo: "architect-gradle-plugin"
    jar: "architect-gradle-plugin.jar"
    loadClass: "io.github.alemazzo.architect.gradle.GradlePlugin"

docs:
  - template: "architect"
  - engine: "asciidoctor"
  - output: "docs"

pipeline:
  - build
  - test
  - release
  - deploy
  - docs
  - notify
  - clean
  - validate
