#!/bin/bash

if [ "$1" == "local" ]; then
  # Install with gradle assemble in architect-cli and moving the jar
  echo "Updating Architect CLI"
  cd architect-cli || exit
  ./gradlew assemble
  rm ../architect-cli.jar
  cp build/libs/architect-cli-0.1-all.jar ../architect-cli.jar
  exit 0
fi

# if jar not present then install and not --local flag then run the jar
if [ ! -f "architect-cli.jar" ]; then
  echo "Installing Architect CLI"
  GITHUB_REPO="alemazzo/architect" # Replace with the GitHub repository (e.g., "alemazzo/architect")
  ASSET_NAME="architect-cli.jar" # Replace with the name of the asset to download
  OUTPUT_DIR="./" # Directory to save the downloaded file

  # Fetch the latest release metadata
  LATEST_RELEASE_URL="https://api.github.com/repos/$GITHUB_REPO/releases/latest"
  ASSET_URL=$(curl -s "$LATEST_RELEASE_URL" | jq -r ".assets[] | select(.name == \"$ASSET_NAME\") | .browser_download_url")

  # Check if the asset URL was found
  if [[ -z "$ASSET_URL" || "$ASSET_URL" == "null" ]]; then
      echo "Error: Asset '$ASSET_NAME' not found in the latest release of '$GITHUB_REPO'."
      exit 1
  fi

  # Download the asset
  echo "Downloading $ASSET_NAME from $ASSET_URL..."
  curl -s -L "$ASSET_URL" --output "$OUTPUT_DIR/$ASSET_NAME"

  if [[ $? -eq 0 ]]; then
      echo "Download complete: $ASSET_NAME"
  else
      echo "Error: Failed to download $ASSET_NAME."
      exit 1
  fi
  echo "Architect CLI installed"
fi

java -jar architect-cli.jar $@
