micronaut:
  application:
    name: architect

architect:
  semantic-release:
    enabled: true
    path: ".architect/plugins/semantic-release"
    command: "./release"
  gradle:
    enabled: true
    path: ".architect/engine/"
    command: "./gradlew"
