name: CI/CD Process
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    if: >-
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.repository
      || startsWith(github.head_ref, 'dependabot/')
    concurrency:
      group: build-${{ github.workflow }}-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - run: ./architect install
      - run: ./architect init
  release:
    runs-on: ubuntu-24.04
    needs: build
    if: >-
      !github.event.repository.fork
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name == github.repository
      )
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - run: ./architect install
      - run: ./architect init
      - run: ./architect release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
