name: pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Environment Setup
    runs-on: ubuntu-latest
    outputs:
      gradle-cache-key: ${{ steps.gradle-cache-key.outputs.key }}
      node-cache-key: ${{ steps.node-cache-key.outputs.key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute Gradle cache key
        id: gradle-cache-key
        run: echo "gradle-key=gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}" >> $GITHUB_OUTPUT

      - name: Compute Node.js cache key
        id: node-cache-key
        run: echo "node-key=node-${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT

  build:
    name: Build Kotlin Project
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.gradle-cache-key }}

      - name: Build CLI
        run: ./gradlew build --info --stacktrace
        working-directory: architect-cli

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-build
          path: architect-cli/build/libs

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle Cache (for tests)
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.gradle-cache-key }}

      - name: Run Tests
        run: ./gradlew test
        working-directory: architect-cli

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle Cache for Release
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs.gradle-cache-key }}

      - name: Run Build (for release)
        run: ./gradlew build
        working-directory: architect-cli

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
